@startuml

skinparam class {
  BackgroundColor #ebebeb
  ArrowColor      #333
  BorderColor     #333
}

skinparam lineType ortho

package md.python.graph {
  interface GraphExceptionInterface {}

  class TopologicalSortException extends GraphExceptionInterface {
    + CYCLE_DETECTED = 1
  }

  interface TopologicalSortInterface <NodeType of typing.Hashable> {
    + sort(graph: GraphType[NodeType]) -> Iterable[NodeType]
  }

  class AscendingTopologicalSort <NodeType of typing.Hashable> {
    + sort(graph: GraphType[NodeType]) -> Iterable[NodeType]
  }

  class DescendingTopologicalSort <NodeType of typing.Hashable> {
    + sort(graph: GraphType[NodeType]) -> Iterable[NodeType]
  }

  AscendingTopologicalSort .left.> TopologicalSortException : raises >
  AscendingTopologicalSort -up-|>  TopologicalSortInterface
  DescendingTopologicalSort -up-|>  TopologicalSortInterface
}

@enduml
